### ISSUE TITLE
Add BCA Discord under 'Join the Bitcoin Cash Community'

### ISSUE THREAD

**Issue by Klakurka** [bitcoincashorg/bitcoincash.org#218]
Add BCA Discord under 'Join the Bitcoin Cash Community'.

https://bitcoincashers.org/chat

Button Icon: logo-discord
Button Text: DISCORD

This is an extremely good channel for Bitcoin Cash discussion that is definitely needs to be included as part of what this community has to offer for new people in the space.

**Comment by BUYMERCIER** [comment]
Cannot approve this request for the following reasons:
- Confusing Bitcoin Cash logo is used (green instead of orange).
- Uncertain moderation of the channel

**Comment by A-Chewy-1** [comment]
Confusing? You realize that block 478559 in which Cash split from cripple coin is hex for green right? If anything keeping the logo orange is confusing.

**Comment by JettScythe** [comment]
Just be glad the BCA didn't go with Im_Uname's sparkly pink suggestions. 
And there is literally a mod team in the members bar. 
Mind giving us the real reason?

**Comment by acidsploit** [comment]
This petty bullshit again? The color of the logo :/

About moderation, BCA discord is arguably the best moderated and managed community in the whole of crypto (that I know of).

Please work together instead of against each other, we're all working towards the same goals.

**Comment by maplesyrupsucker** [comment]
While our listing criteria encourages the use of orange, it is not required. We do expedite listings though that are willing to work with us. But I'd like it to be made clear this isn't a denial based on color. Bikeshedding should have left with the C.O.C. 

Paul, Monica, Collin and Wecx are indeed valuable members of the community. I've met several of them IRL, and I agree they're good folks. 

When it comes to the social and community chats listings we felt listing requirements should ensure one of our website admins have some form of administrative capabilities. I won't go into the entire history of the situation, but for contex, a bit of backstory is probably needed. In essence, we were never offered a seat at that table, though would gladly accept should they be willing. 

There was some concern from back in 2017 that BCA was choosing to do their own thing rather than work with the community at large. It's likely the easier option from their POV, and allowed them to move faster. But at the cost of creating a bit of a divide. I myself have struggled having to work together with all the different parties and iron out differences amongst those contributing to BitcoinCash.org. It's difficult. But working together imho is the best way to avoid the creation of competing tribes. We all share the same goal of spreading Bitcoin Cash. This is bigger than any one group. There was also some concern amongst the work group here that BitcoinCashers.org is confusing for new users as it is awefully close to BitcoinCash.org and some saw it as a fairly large middle finger to the contributors of this repo. While it's a nice site, there was never a PR made from their repo to ours. 

So in the Christmas spirit I'm going to reopen this PR for discussion. This might be a good opportunity for both sides to come together and discuss how we can unite our efforts. Let's try to build bridges here.

**Comment by Klakurka** [comment]
@maplesyrupsucker

In my discussions with various people throughout the community, better communication and collaboration is something that everyone seems to agree on.

I know that there are changes planned for bitcoincashers.org which I think will be a benefit for everyone.

**Comment by imaginaryusername** [comment]
@maplesyrupsucker thanks for the kind words and background. These are different times now, and I personally think there no longer is a need for various organizations to enforce standard practices against each other; linking, an ackowledgement that the other site/place is a significant part of the Bitcoin Cash community that is beneficial and non-malicious, should come with as few strings as possible. 

While some will feel bitcoincashers is "redundant" and "a middle finger", whatever the historical context (note: the grievances go both ways) it's just another informational outlet, just as bitcoincashorg is - granted the latter is one with the easier to recognize domain. I'll recommend both sites link to each other.

And with that said, the discord channel, taking a life of its own well beyond BCA-sponsored projects, isn't even directly responsible for it. Regardless of the considerations on bitcoincashers, adding the discord link seems like a no-brainer and is a net benefit for the everyone.

**Comment by cheaplightning** [comment]
> 
> 
> @maplesyrupsucker thanks for the kind words and background. These are different times now, and I personally think there no longer is a need for various organizations to enforce standard practices against each other; linking, an ackowledgement that the other site/place is a significant part of the Bitcoin Cash community that is beneficial and non-malicious, should come with as few strings as possible.
> 
> While some will feel bitcoincashers is "redundant" and "a middle finger", whatever the historical context (note: the grievances go both ways) it's just another informational outlet, just as bitcoincashorg is - granted the latter is one with the easier to recognize domain. I'll recommend both sites link to each other.
> 
> And with that said, the discord channel, taking a life of its own well beyond BCA-sponsored projects, isn't even directly responsible for it. Regardless of the considerations on bitcoincashers, adding the discord link seems like a no-brainer and is a net benefit for the everyone.

I can not agree more.

**Comment by merc1er** [comment]
PR #406 solves this.
@maplesyrupsucker please review.

I am closing this, if the PR is not approved for some reason please continue discussion in #406
